name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags, e.g., v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.0'  # Use the version of Go you need

    - name: Build binaries for multiple platforms
      run: |
        mkdir -p build
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o build/awswhoiam_linux_amd64 ./main.go
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o build/awswhoiam_windows_amd64.exe ./main.go
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o build/awswhoiam_darwin_amd64 ./main.go

    - name: Upload Release Assets
      uses: actions/upload-artifact@v4
      with:
        name: awswhoiam
        path: ./build/*
